---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 16.03.2022 12:58
---


local _, E = ...

st = E.SPELL_TOOLS

function E:addBaseData()
    if not UnitAffectingCombat("Player") then
        E.active = false
    end

    E.serializationData.act = E.active;

    E.addHealthAndEnergyValues()
    E.addCastingInfoValues()
    E.addThreatInfoValues()

    E.serializationData.potionCD = E.getGeneralPotionCD() > 0
end

function E.addHealthAndEnergyValues()
    E.serializationData.mh = UnitHealthMax("player");
    E.serializationData.ah = UnitHealth("player");

    E.serializationData.maxMana = UnitPowerMax("player", 0);
    E.serializationData.mana = UnitPower("player", 0);

    E.serializationData.maxRage = UnitPowerMax("player", 1);
    E.serializationData.rage = UnitPower("player", 1);

    E.serializationData.maxEnergy = UnitPowerMax("player", 3);
    E.serializationData.energy = UnitPower("player", 3);

    E.serializationData.run = E.isRunning()

    if (UnitName("target") == nil) then
        E.serializationData.tn = ""
    else
        E.serializationData.tn = UnitName("target")

    end

    E.serializationData.th = UnitHealth("target");

end

function E.addCastingInfoValues()
    local spellName, _, _, _, spellEndTime = UnitCastingInfo("player")
    local channelName, _, _, _, channelEndTime = UnitChannelInfo("player")

    if not (spellName == nil) then
        E.serializationData.cast = "SPELL"
        E.serializationData.castTimeRem = spellEndTime / 1000 - GetTime()

    elseif not (channelName == nil) then
        E.serializationData.cast = "CHANNEL"
        E.serializationData.castTimeRem = channelEndTime / 1000 - GetTime()

    else
        E.serializationData.cast = "NONE"
        E.serializationData.castTimeRem = -1
    end

end

function E.addThreatInfoValues()
    local isTanking, status, scaledPercentage, rawPercentage, threatValue = UnitDetailedThreatSituation("player", "target")

    E.serializationData.thtIT = isTanking;
    E.serializationData.thtS = status;
    E.serializationData.thtSP = scaledPercentage;
    E.serializationData.thtRP = rawPercentage;
    E.serializationData.thtV = threatValue;
end

function E:isRunning()
    currentSpeed, _, _, _ = GetUnitSpeed("player")
    return currentSpeed > 0
end

function E:getGeneralPotionCD()
    return st.getItemCD(self, 22832) -- Super mana potion
end
