---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 16.03.2022 12:54
---

local _, E = ...

E.CONFIGURATION = {
    SIZE_X = GetScreenWidth() - 4,
    SIZE_Y = 10,
    BORDER = 2,
    SQUARE_COUNT = 300,
    UPDATE_TIME = 0.1
}

E.lastUpdateTime = GetTime();

function E:initFrameComFrame()
    E.baseFrame = E.createBaseFrame()
    E.createInnerSquares();
    E.baseFrame:SetScript("OnUpdate", E.update)
end

function E:createInnerSquares()
    E.innerTextures = {};
    local squareSize = E.CONFIGURATION.SIZE_X / E.CONFIGURATION.SQUARE_COUNT

    for i = 1, E.CONFIGURATION.SQUARE_COUNT do

        local t = E.baseFrame:CreateTexture(nil, "HIGHLIGHT ")
        t:SetColorTexture(1, 1, 1, 1);
        t:SetSize(squareSize, E.CONFIGURATION.SIZE_Y)
        t:SetPoint("BOTTOMLEFT", (i - 1) * squareSize + E.CONFIGURATION.BORDER, E.CONFIGURATION.BORDER)

        E.innerTextures[i] = t
    end
end

function E:update()

    local actualTime = GetTime();
    if actualTime - E.lastUpdateTime < E.CONFIGURATION.UPDATE_TIME then
        return
    end

    E.serializationData = {}
    E.addBaseData()
    if not (E.ACTUAL_CONFIGURATION == nil) then
        E.ACTUAL_CONFIGURATION.update()
    end

    E.updateComBar()

    E.lastUpdateTime = GetTime();
end

function E:updateComBar()
    local data = E.json.encode(E.serializationData)

    for x = 1, E.CONFIGURATION.SQUARE_COUNT do
        local t = E.innerTextures[x]

        local r = 0;
        local g = 0;
        local b = 0;

        if (x * 3 - 2 <= #data) then
            r = string.byte(data, x * 3 - 2) / 255
        end

        if (x * 3 - 1 <= #data) then
            g = string.byte(data, x * 3 - 1) / 255
        end

        if (x * 3 <= #data) then
            b = string.byte(data, x * 3) / 255
        end

        t:SetColorTexture(r, g, b, 1);
    end

end

function E:createBaseFrame()
    local baseFrame = CreateFrame("Frame", "ComFrame", UIParent)
    baseFrame:SetFrameStrata("TOOLTIP")
    baseFrame:SetWidth(E.CONFIGURATION.SIZE_X + 2 * E.CONFIGURATION.BORDER)
    baseFrame:SetHeight(E.CONFIGURATION.SIZE_Y + 2 * E.CONFIGURATION.BORDER)

    local t = baseFrame:CreateTexture(nil, "BACKGROUND")
    t:SetColorTexture(1.0, 1.0, 0.0, 1);
    t:SetAllPoints(baseFrame)
    baseFrame.texture = t

    baseFrame:SetPoint("CENTER", 0, 0)
    baseFrame:SetMovable(true)
    baseFrame:EnableMouse(true)
    baseFrame:RegisterForDrag("LeftButton")
    baseFrame:SetScript("OnDragStart", baseFrame.StartMoving)
    baseFrame:SetScript("OnDragStop", baseFrame.StopMovingOrSizing)
    baseFrame:Show()
    print("base frame initialized")
    return baseFrame
end

