---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 29.03.2022 11:11
---

local _, E = ...

function E:initAddon()
    E.initCommunication()
    E.initProfiles()
end

function E:initCommunication()
    E:initFrameComFrame()
end

function E:initProfiles()
    for key, value in pairs(E.CLASS_CONFIGURATIONS) do
        value['init']()
    end
end

function E:loadProfile(profile)
    E.unloadProfile()

    E.ACTUAL_CONFIGURATION = profile

    print("Loading " .. E.ACTUAL_CONFIGURATION['profileName'])
    E.ACTUAL_CONFIGURATION['load']()

end

function E:unloadProfile()
    if E.ACTUAL_CONFIGURATION == nil then
        print("Nothing to unload")
    else
        print("Unloading " .. E.ACTUAL_CONFIGURATION['profileName'])
        E.ACTUAL_CONFIGURATION['unload']()
        E.ACTUAL_CONFIGURATION = nil
    end
end

_G.SLASH_ROTATOR1 = "/rot"
_G.SLASH_ROTATOR2 = "/rotator"

function SlashCmdList.ROTATOR(msg)
    chunks = {}
    for substring in msg:gmatch("%S+") do
        table.insert(chunks, substring)
    end

    if chunks[1] == "profiles" then
        for key, value in pairs(E.CLASS_CONFIGURATIONS) do
            print(value['profileName'])
        end
    end
    if chunks[1] == "select" then
        for key, value in pairs(E.CLASS_CONFIGURATIONS) do
            if value['profileName'] == chunks[2] then
                E:loadProfile(value)
            end
        end
    end

    if chunks[1] == "unload" then
        E.unloadProfile()
    end
end




