---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 29.03.2022 15:13
---

local _, E = ...

E.CLASS_CONFIGURATIONS = {}
E.ACTUAL_CONFIGURATION = nil
E.active = false;

E.CONSTANTS = {}
E.CONSTANTS.PRECAST_TIME = 0.2