---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 17.03.2022 13:04
---


function isUsableSpell(spellname)
    local usable = IsUsableSpell(spellname)
    local start, duration = GetSpellCooldown(spellname)
    local isCooldown = start > 0 and duration > 0

    return usable and not isCooldown
end

function isUsableBySpellAndDebuff(spellname, debuffname, playerAura, remainingTime)

    local usable = IsUsableSpell(spellname)
    local start, duration = GetSpellCooldown(spellname)
    local isCooldown = start > 0 and duration > 0
    local isAura = isAuraOnTarget(debuffname, playerAura, remainingTime);

    return usable and not isCooldown and not isAura
end

function isAuraOnTarget(auraname, playerAura, remainingTime)
    for i = 0, 40 do
        local modifier = "HARMFUL";
        if (playerAura) then
            modifier = "HARMFUL|PLAYER";
        end

        local name, _, _, _, _, expirationTime = UnitAura("target", i, modifier)

        if (auraname == name) then
            local actualRemainingTime = expirationTime - GetTime();

            if (actualRemainingTime < remainingTime) then
                return false
            end
            return true
        end
    end

    return false;
end

function getSpellCD(spellID)
    local startTime, duration = GetSpellCooldown(spellID)
    return startTime + duration - GetTime()
end

function getItemCD(itemID)
    local startTime, duration, enable = GetItemCooldown(itemID)
    return startTime + duration - GetTime()
end

function getTrinket1CD()
    return getInventoryItemCD(13)
end

function getTrinket2CD()
    return getInventoryItemCD(14)
end

function getInventoryItemCD(itemSlot)
    local startTime, duration, enable = GetInventoryItemCooldown("player", itemSlot)
    return startTime + duration - GetTime()
end

function splitString (inputstr, sep)
    if sep == nil then
        sep = "%s"
    end
    local t = {}
    for str in string.gmatch(inputstr, "([^" .. sep .. "]+)") do
        table.insert(t, str)
    end
    return t
end