---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 02.03.2022 9:34
---
local _, E = ...

E.BALANCED_DRUID_DATA = {}
balaDruid = E.BALANCED_DRUID_DATA
bf = E.BUTTON_FACTORY
st = E.SPELL_TOOLS

function balaDruid:initBalanceDruid()
    print("Initializing BALA")

    balaDruid.frame = CreateFrame("Frame", "BDruidFrame", UIParent)

    balaDruid.frame:SetFrameStrata("TOOLTIP")
    balaDruid.frame:SetWidth(150)
    balaDruid.frame:SetHeight(120)

    balaDruid.combatTexture = balaDruid.frame:CreateTexture(nil, "BACKGROUND")
    balaDruid.combatTexture:SetPoint("BOTTOMLEFT", 0, 90)
    balaDruid.combatTexture:SetSize(30, 30)


    balaDruid.activeTexture = balaDruid.frame:CreateTexture(nil, "BACKGROUND")
    balaDruid.activeTexture:SetPoint("BOTTOMLEFT", 30, 90)
    balaDruid.activeTexture:SetSize(120, 30)

    balaDruid.toggleButtons = {}
    balaDruid.activatingButtons = {}

    bf.setGlobalVariables(self, 30,30)

    balaDruid.toggleButtons.moonFireButton = bf.createToggleButton(self,0,2, balaDruid.frame, 136096)
    balaDruid.toggleButtons.starFireButton = bf.createToggleButton(self,1,2, balaDruid.frame, 135753)
    balaDruid.toggleButtons.insectSwarmButton = bf.createToggleButton(self,2,2, balaDruid.frame, 136045)
    balaDruid.toggleButtons.faerieFireButton = bf.createToggleButton(self,3,2, balaDruid.frame, 136033)
    balaDruid.toggleButtons.runModeButton = bf.createToggleButton(self,4,2, balaDruid.frame, 132539)

    balaDruid.toggleButtons.threatLockButton = bf.createToggleButton(self,4,0, balaDruid.frame, 136150)

    balaDruid.activatingButtons.trinket1Button = bf.createTrinket1ActivatingButton(self,0,1, balaDruid.frame, 135659)
    -- balaDruid.activatingButtons.drumsButton = bf.createItemActivatingButton(self,1,1, balaDruid.frame, 133842, 185848)
    balaDruid.activatingButtons.destructionPotionButton = bf.createItemActivatingButton(self,0,0, balaDruid.frame, 134729, 22839)


    balaDruid.activatingButtons.manaPotionButton = bf.createItemActivatingButton(self,3,1, balaDruid.frame, 134762,22832)
    balaDruid.activatingButtons.darkRuneButton = bf.createItemActivatingButton(self,4,1, balaDruid.frame, 136192, 20520)
    balaDruid.activatingButtons.innervateButton = bf.createSpellActivatingButton(self,3,0, balaDruid.frame, 136048, 29166)


    balaDruid.frame:SetPoint("CENTER", 0, 0)
    balaDruid.frame:SetMovable(true)
    balaDruid.frame:EnableMouse(true)
    balaDruid.frame:RegisterForDrag("LeftButton")
    balaDruid.frame:SetScript("OnDragStart", balaDruid.frame.StartMoving)
    balaDruid.frame:SetScript("OnDragStop", balaDruid.frame.StopMovingOrSizing)

    balaDruid.actualizeFrame()
    balaDruid.frame:Hide()

end

function balaDruid:loadBalanceDruid()
    balaDruid.frame:Show()
    print("Loading BALA")
end

function balaDruid:unloadBalanceDruid()
    balaDruid.frame:Hide()
    print("Unloading BALA")
end

function balaDruid:updateBalanceDruid()

    local serializationData = E.serializationData

    serializationData.profile = "bd_01";

    serializationData.pmfd = st.isUsableBySpellAndDebuff(self,"Moonfire", "Moonfire", true, 0)
    serializationData.pmf = st.isUsableSpell(self,"Moonfire")
    serializationData.psf = st.isUsableSpell(self,"Starfire")
    serializationData.pff = st.isUsableBySpellAndDebuff(self,"Faerie Fire", "Faerie Fire", false, 5)
    serializationData.pis = st.isUsableBySpellAndDebuff(self,"Insect Swarm", "Insect Swarm", false, 2)

    serializationData.emf = balaDruid.toggleButtons.moonFireButton.value
    serializationData.esf = balaDruid.toggleButtons.starFireButton.value
    serializationData.eff = balaDruid.toggleButtons.faerieFireButton.value
    serializationData.eis = balaDruid.toggleButtons.insectSwarmButton.value
    serializationData.rm = balaDruid.toggleButtons.runModeButton.value

    serializationData.tl = balaDruid.toggleButtons.threatLockButton.value

    serializationData.amp = balaDruid.activatingButtons.manaPotionButton.isActivated()
    serializationData.adr = balaDruid.activatingButtons.darkRuneButton.isActivated()
    serializationData.at = balaDruid.activatingButtons.trinket1Button.isActivated()
    -- serializationData.ad = balaDruid.activatingButtons.drumsButton.isActivated()
    serializationData.ai = balaDruid.activatingButtons.innervateButton.isActivated()
    serializationData.adp = balaDruid.activatingButtons.destructionPotionButton.isActivated()

    balaDruid.actualizeFrame()
end

function balaDruid:actualizeFrame()
    if UnitAffectingCombat("Player") then
        balaDruid.combatTexture:SetColorTexture(0,1,0,0.5)
    else
        balaDruid.combatTexture:SetColorTexture(1,0,0,0.5)
    end

    if E.active then
        balaDruid.activeTexture:SetColorTexture(0,1,0,0.5)
    else
        if UnitAffectingCombat("Player") then
            balaDruid.activeTexture:SetColorTexture(1,0.5,0,0.5)
        else
            balaDruid.activeTexture:SetColorTexture(1,0,0,0.5)
        end
    end


    balaDruid.toggleButtons.moonFireButton.update()
    balaDruid.toggleButtons.starFireButton.update()
    balaDruid.toggleButtons.insectSwarmButton.update()
    balaDruid.toggleButtons.faerieFireButton.update()
    balaDruid.toggleButtons.runModeButton.update()
    balaDruid.toggleButtons.threatLockButton.update()

    balaDruid.activatingButtons.trinket1Button.update()
    balaDruid.activatingButtons.destructionPotionButton.update()
    balaDruid.activatingButtons.manaPotionButton.update()
    balaDruid.activatingButtons.darkRuneButton.update()
    balaDruid.activatingButtons.innervateButton.update()

end

E.CLASS_CONFIGURATIONS["DRUID_BALANCE"] = {
    ['profileName'] = 'balance',
    ['init'] = balaDruid.initBalanceDruid,
    ['load'] = balaDruid.loadBalanceDruid,
    ['unload'] = balaDruid.unloadBalanceDruid,
    ['update'] = balaDruid.updateBalanceDruid,
    ['toggleFunctions'] = {}
}
