---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 02.03.2022 9:34
---
local _, E = ...

E.BALANCED_DRUID_WOTLK_01_DATA = {}
balaDruidWotlk_01 = E.BALANCED_DRUID_WOTLK_01_DATA
bf = E.BUTTON_FACTORY
st = E.SPELL_TOOLS

function balaDruidWotlk_01:initBalanceDruid()
    print("Initializing BALA WOTLK")

    balaDruidWotlk_01.frame = CreateFrame("Frame", "BDruidWOTLKFrame", UIParent)

    balaDruidWotlk_01.frame:SetFrameStrata("TOOLTIP")
    balaDruidWotlk_01.frame:SetWidth(150)
    balaDruidWotlk_01.frame:SetHeight(120)

    balaDruidWotlk_01.combatTexture = balaDruidWotlk_01.frame:CreateTexture(nil, "BACKGROUND")
    balaDruidWotlk_01.combatTexture:SetPoint("BOTTOMLEFT", 0, 90)
    balaDruidWotlk_01.combatTexture:SetSize(30, 30)


    balaDruidWotlk_01.activeTexture = balaDruidWotlk_01.frame:CreateTexture(nil, "BACKGROUND")
    balaDruidWotlk_01.activeTexture:SetPoint("BOTTOMLEFT", 30, 90)
    balaDruidWotlk_01.activeTexture:SetSize(120, 30)

    balaDruidWotlk_01.toggleButtons = {}
    balaDruidWotlk_01.activatingButtons = {}
    balaDruidWotlk_01.switchButtons = {}

    bf.setGlobalVariables(self, 30,30)

    balaDruidWotlk_01.toggleButtons.starFallButton = bf.createToggleButton(self,2,2, balaDruidWotlk_01.frame, 236168)
    balaDruidWotlk_01.toggleButtons.faerieFireButton = bf.createToggleButton(self,3,2, balaDruidWotlk_01.frame, 136033)
    balaDruidWotlk_01.toggleButtons.threatLockButton = bf.createToggleButton(self,4,0, balaDruidWotlk_01.frame, 136150)
    balaDruidWotlk_01.toggleButtons.moonFireButton = bf.createToggleButton(self,0,2, balaDruidWotlk_01.frame, 136096)
    balaDruidWotlk_01.toggleButtons.insectSwarmButton = bf.createToggleButton(self,1,2, balaDruidWotlk_01.frame, 136045)


    balaDruidWotlk_01.activatingButtons.trinket1Button = bf.createTrinket1ActivatingButton(self,0,1, balaDruidWotlk_01.frame, 135659)
    balaDruidWotlk_01.activatingButtons.destructionPotionButton = bf.createItemActivatingButton(self,0,0, balaDruidWotlk_01.frame, 134729, 22839)
    balaDruidWotlk_01.activatingButtons.manaPotionButton = bf.createItemActivatingButton(self,3,1, balaDruidWotlk_01.frame, 134762,22832)
    balaDruidWotlk_01.activatingButtons.darkRuneButton = bf.createItemActivatingButton(self,4,1, balaDruidWotlk_01.frame, 136192, 20520)
    balaDruidWotlk_01.activatingButtons.innervateButton = bf.createSpellActivatingButton(self,3,0, balaDruidWotlk_01.frame, 136048, 29166)


    balaDruidWotlk_01.frame:SetPoint("CENTER", 0, 0)
    balaDruidWotlk_01.frame:SetMovable(true)
    balaDruidWotlk_01.frame:EnableMouse(true)
    balaDruidWotlk_01.frame:RegisterForDrag("LeftButton")
    balaDruidWotlk_01.frame:SetScript("OnDragStart", balaDruidWotlk_01.frame.StartMoving)
    balaDruidWotlk_01.frame:SetScript("OnDragStop", balaDruidWotlk_01.frame.StopMovingOrSizing)

    balaDruidWotlk_01.actualizeFrame()
    balaDruidWotlk_01.frame:Hide()

end

function balaDruidWotlk_01:loadBalanceDruid()
    balaDruidWotlk_01.frame:Show()
    print("Loading BALA")
end

function balaDruidWotlk_01:unloadBalanceDruid()
    balaDruidWotlk_01.frame:Hide()
    print("Unloading BALA")
end

function balaDruidWotlk_01:updateBalanceDruid()

    local serializationData = E.serializationData

    serializationData.profile = "bd_wotlk_01";

    serializationData.tl = balaDruidWotlk_01.toggleButtons.threatLockButton.value

    serializationData.esfa = balaDruidWotlk_01.toggleButtons.starFallButton.value
    serializationData.eff = balaDruidWotlk_01.toggleButtons.faerieFireButton.value
    serializationData.emf = balaDruidWotlk_01.toggleButtons.moonFireButton.value
    serializationData.eis = balaDruidWotlk_01.toggleButtons.insectSwarmButton.value


    serializationData.psf = st.isUsableSpell(self,"Starfire")
    serializationData.pw = st.isUsableSpell(self,"Wrath")
    serializationData.psfa = st.isUsableSpell(self,"StarFall")
    serializationData.pff = st.isUsableBySpellAndDebuff(self,"Faerie Fire", "Faerie Fire", false, 5)
    serializationData.pmfd = st.isUsableBySpellAndDebuff(self,"Moonfire", "Moonfire", true, 0)
    serializationData.pis = st.isUsableBySpellAndDebuff(self,"Insect Swarm", "Insect Swarm", false, 0)


    serializationData.amp = balaDruidWotlk_01.activatingButtons.manaPotionButton.isActivated()
    serializationData.adr = balaDruidWotlk_01.activatingButtons.darkRuneButton.isActivated()
    serializationData.at = balaDruidWotlk_01.activatingButtons.trinket1Button.isActivated()
    serializationData.ai = balaDruidWotlk_01.activatingButtons.innervateButton.isActivated()
    serializationData.adp = balaDruidWotlk_01.activatingButtons.destructionPotionButton.isActivated()

    serializationData.sea = st.isAuraOnPlayer(self, "Eclipse (Solar)",  0)
    serializationData.lea = st.isAuraOnPlayer(self, "Eclipse (Lunar)",  0)



    balaDruidWotlk_01.actualizeFrame()
end

function balaDruidWotlk_01:actualizeFrame()
    if UnitAffectingCombat("Player") then
        balaDruidWotlk_01.combatTexture:SetColorTexture(0,1,0,0.5)
    else
        balaDruidWotlk_01.combatTexture:SetColorTexture(1,0,0,0.5)
    end

    if E.active then
        balaDruidWotlk_01.activeTexture:SetColorTexture(0,1,0,0.5)
    else
        if UnitAffectingCombat("Player") then
            balaDruidWotlk_01.activeTexture:SetColorTexture(1,0.5,0,0.5)
        else
            balaDruidWotlk_01.activeTexture:SetColorTexture(1,0,0,0.5)
        end
    end

    balaDruidWotlk_01.toggleButtons.threatLockButton.update()

    balaDruidWotlk_01.toggleButtons.starFallButton.update()
    balaDruidWotlk_01.toggleButtons.faerieFireButton.update()
    balaDruidWotlk_01.toggleButtons.moonFireButton.update()
    balaDruidWotlk_01.toggleButtons.insectSwarmButton.update()

    balaDruidWotlk_01.activatingButtons.trinket1Button.update()
    balaDruidWotlk_01.activatingButtons.destructionPotionButton.update()
    balaDruidWotlk_01.activatingButtons.manaPotionButton.update()
    balaDruidWotlk_01.activatingButtons.darkRuneButton.update()
    balaDruidWotlk_01.activatingButtons.innervateButton.update()

    balaDruidWotlk_01.activatingButtons.innervateButton.update()
    balaDruidWotlk_01.activatingButtons.innervateButton.update()

end

E.CLASS_CONFIGURATIONS["DRUID_BALANCE_WOTLK"] = {
    ['profileName'] = 'balance_wotlk',
    ['init'] = balaDruidWotlk_01.initBalanceDruid,
    ['load'] = balaDruidWotlk_01.loadBalanceDruid,
    ['unload'] = balaDruidWotlk_01.unloadBalanceDruid,
    ['update'] = balaDruidWotlk_01.updateBalanceDruid,
    ['toggleFunctions'] = {}
}
