---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 02.03.2022 9:34
---
local _, E = ...

E.BALANCED_DRUID_DATA = {}

function E:initBalanceDruid()
    print("Initializing BALA")
    local data = E.BALANCED_DRUID_DATA

    data.balDruidFrame = CreateFrame("Frame", "BDruidFrame", UIParent)

    data.balDruidFrame:SetFrameStrata("TOOLTIP")
    data.balDruidFrame:SetWidth(150)
    data.balDruidFrame:SetHeight(90)

    data.combatTexture = data.balDruidFrame:CreateTexture(nil, "BACKGROUND")
    data.combatTexture:SetPoint("BOTTOMLEFT", 0, 60)
    data.combatTexture:SetSize(30, 30)


    data.activeTexture = data.balDruidFrame:CreateTexture(nil, "BACKGROUND")
    data.activeTexture:SetPoint("BOTTOMLEFT", 30, 60)
    data.activeTexture:SetSize(120, 30)

    _, data.mfTexture = E.createPanelSwitchButton(self, 0, 30, 30, 30, data.balDruidFrame, 136096,
            function()
                E.BALANCED_DRUID_DATA.moonfireEnabled = not E.BALANCED_DRUID_DATA.moonfireEnabled
                E.actualizeBalanceDruidFrame()
            end)

    _, data.sfTexture = E.createPanelSwitchButton(self, 30, 30, 30, 30, data.balDruidFrame, 135753,
            function()
                E.BALANCED_DRUID_DATA.starfireEnabled = not E.BALANCED_DRUID_DATA.starfireEnabled
                E.actualizeBalanceDruidFrame()
            end)

    _, data.isTexture = E.createPanelSwitchButton(self, 60, 30, 30, 30, data.balDruidFrame, 136045,
            function()
                E.BALANCED_DRUID_DATA.isEnabled = not E.BALANCED_DRUID_DATA.isEnabled
                E.actualizeBalanceDruidFrame()
            end)

    _, data.ffTexture = E.createPanelSwitchButton(self, 90, 30, 30, 30, data.balDruidFrame, 136033,
            function()
                E.BALANCED_DRUID_DATA.ffEnabled = not E.BALANCED_DRUID_DATA.ffEnabled
                E.actualizeBalanceDruidFrame()
            end)

    _, data.rmTexture = E.createPanelSwitchButton(self, 120, 30, 30, 30, data.balDruidFrame, 132539,
            function()
                E.BALANCED_DRUID_DATA.isRunningModeEnable = not E.BALANCED_DRUID_DATA.isRunningModeEnable
                E.actualizeBalanceDruidFrame()
            end)


    _, data.activateManaPotionTexture = E.createPanelSwitchButton(self, 0, 0, 30, 30, data.balDruidFrame, 134762,
            function()
                E.BALANCED_DRUID_DATA.activateManaPotion = true
                C_Timer.After(15, function()  E.BALANCED_DRUID_DATA.activateManaPotion = false end)
                E.actualizeBalanceDruidFrame()
            end)

    _, data.activateDarkRuneTexture = E.createPanelSwitchButton(self, 30, 0, 30, 30, data.balDruidFrame, 136192,
            function()
                E.BALANCED_DRUID_DATA.activateDarkRune = true
                C_Timer.After(15, function()  E.BALANCED_DRUID_DATA.activateDarkRune = false end)
                E.actualizeBalanceDruidFrame()
            end)

    _, data.activateTrinketTexture = E.createPanelSwitchButton(self, 60, 0, 30, 30, data.balDruidFrame, 135659,
            function()
                E.BALANCED_DRUID_DATA.activateTrinket = true
                C_Timer.After(15, function()  E.BALANCED_DRUID_DATA.activateTrinket = false end)
                E.actualizeBalanceDruidFrame()
            end)

    _, data.activateDrumsTexture = E.createPanelSwitchButton(self, 90, 0, 30, 30, data.balDruidFrame, 133842,
            function()
                E.BALANCED_DRUID_DATA.activateDrums = true
                C_Timer.After(15, function()  E.BALANCED_DRUID_DATA.activateDrums = false end)
                E.actualizeBalanceDruidFrame()
            end)

    _, data.activateInnervateTexture = E.createPanelSwitchButton(self, 120, 0, 30, 30, data.balDruidFrame, 136048,
            function()
                E.BALANCED_DRUID_DATA.activateInnervate = true
                C_Timer.After(15, function()  E.BALANCED_DRUID_DATA.activateInnervate = false end)
                E.actualizeBalanceDruidFrame()
            end)




    data.balDruidFrame:SetPoint("CENTER", 0, 0)
    data.balDruidFrame:SetMovable(true)
    data.balDruidFrame:EnableMouse(true)
    data.balDruidFrame:RegisterForDrag("LeftButton")
    data.balDruidFrame:SetScript("OnDragStart", data.balDruidFrame.StartMoving)
    data.balDruidFrame:SetScript("OnDragStop", data.balDruidFrame.StopMovingOrSizing)

    data.moonfireEnabled = false
    data.starfireEnabled = false
    data.ffEnabled = false
    data.isEnabled = false
    data.isRuningModeEnable = false
    data.activateManaPotion = false
    data.activateDarkRune = false
    data.activateTrinket = false
    data.activateDrums = false
    data.activateInnervate = false

    E.actualizeBalanceDruidFrame()
    data.balDruidFrame:Hide()

end

function E:createPanelSwitchButton(x, y, width, height, parent, icon, switchFunction)
    print(parent)

    local button = CreateFrame("Button", nil, parent)
    button:SetPoint("BOTTOMLEFT", x, y)
    button:SetSize(width, height)

    button:RegisterForClicks("AnyUp")
    button:SetScript("OnClick", switchFunction)

    local texture = button:CreateTexture(nil, "BACKGROUND")
    texture:SetPoint("BOTTOMLEFT", 0, 0)
    texture:SetSize(30, 30)
    texture:SetTexture(icon);

    local overlayTexture = button:CreateTexture(nil, "OVERLAY" )
    overlayTexture:SetPoint("BOTTOMLEFT", 0, 0)
    overlayTexture:SetSize(30, 30)

    return button, overlayTexture
end

function E:loadBalanceDruid()
    E.BALANCED_DRUID_DATA.balDruidFrame:Show()
    print("Loading BALA")
end

function E:unloadBalanceDruid()
    E.BALANCED_DRUID_DATA.balDruidFrame:Hide()
    print("Unloading BALA")
end

function E:updateBalanceDruid()
    E.serializationData.profile = "bd_01";

    E.serializationData.pmfd = isUsableBySpellAndDebuff("Moonfire", "Moonfire", true, 0)
    E.serializationData.pmf = isUsableSpell("Moonfire")
    E.serializationData.psf = isUsableSpell("Starfire")
    E.serializationData.pff = isUsableBySpellAndDebuff("Faerie Fire", "Faerie Fire", false, 5)
    E.serializationData.pis = isUsableBySpellAndDebuff("Insect Swarm", "Insect Swarm", false, 2)

    if E.BALANCED_DRUID_DATA.activateManaPotion and getItemCD(22832) > 2 then E.BALANCED_DRUID_DATA.activateManaPotion = false end
    if E.BALANCED_DRUID_DATA.activateDarkRune and getItemCD(20520) > 2 then E.BALANCED_DRUID_DATA.activateDarkRune = false end
    if E.BALANCED_DRUID_DATA.activateTrinket and getTrinket1CD() > 2 then E.BALANCED_DRUID_DATA.activateTrinket = false end
    if E.BALANCED_DRUID_DATA.activateDrums and getItemCD(185848) > 2 then E.BALANCED_DRUID_DATA.activateDrums = false end
    if E.BALANCED_DRUID_DATA.activateInnervate and getSpellCD(29166) > 2 then E.BALANCED_DRUID_DATA.activateInnervate = false end


    E.serializationData.emf = E.BALANCED_DRUID_DATA.moonfireEnabled
    E.serializationData.esf = E.BALANCED_DRUID_DATA.starfireEnabled
    E.serializationData.eff = E.BALANCED_DRUID_DATA.ffEnabled
    E.serializationData.eis = E.BALANCED_DRUID_DATA.isEnabled
    E.serializationData.rm = E.BALANCED_DRUID_DATA.isRunningModeEnable

    E.serializationData.amp = E.BALANCED_DRUID_DATA.activateManaPotion
    E.serializationData.adr = E.BALANCED_DRUID_DATA.activateDarkRune
    E.serializationData.at = E.BALANCED_DRUID_DATA.activateTrinket
    E.serializationData.ad = E.BALANCED_DRUID_DATA.activateDrums
    E.serializationData.ai = E.BALANCED_DRUID_DATA.activateInnervate

    E.actualizeBalanceDruidFrame()
end

function E:actualizeBalanceDruidFrame()
    if UnitAffectingCombat("Player") then
        E.BALANCED_DRUID_DATA.combatTexture:SetColorTexture(0,1,0,0.5)
    else
        E.BALANCED_DRUID_DATA.combatTexture:SetColorTexture(1,0,0,0.5)
    end

    if E.active then
        E.BALANCED_DRUID_DATA.activeTexture:SetColorTexture(0,1,0,0.5)
    else
        if UnitAffectingCombat("Player") then
            E.BALANCED_DRUID_DATA.activeTexture:SetColorTexture(1,0.5,0,0.5)
        else
            E.BALANCED_DRUID_DATA.activeTexture:SetColorTexture(1,0,0,0.5)
        end
    end

    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.mfTexture, E.BALANCED_DRUID_DATA.moonfireEnabled)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.sfTexture, E.BALANCED_DRUID_DATA.starfireEnabled)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.isTexture, E.BALANCED_DRUID_DATA.isEnabled)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.ffTexture, E.BALANCED_DRUID_DATA.ffEnabled)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.rmTexture, E.BALANCED_DRUID_DATA.isRunningModeEnable)

    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.activateManaPotionTexture, E.BALANCED_DRUID_DATA.activateManaPotion)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.activateDarkRuneTexture, E.BALANCED_DRUID_DATA.activateDarkRune)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.activateTrinketTexture, E.BALANCED_DRUID_DATA.activateTrinket)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.activateDrumsTexture, E.BALANCED_DRUID_DATA.activateDrums)
    E.actualizeSwitchButtonTexture(self, E.BALANCED_DRUID_DATA.activateInnervateTexture, E.BALANCED_DRUID_DATA.activateInnervate)

end

function E:actualizeSwitchButtonTexture(texture, value)
    if value then
        texture:SetDesaturated(true);
        texture:SetColorTexture(0,1,0,0.0)
    else
        texture:SetDesaturated(false);
        texture:SetColorTexture(1,0,0,0.5)
    end
end

E.CLASS_CONFIGURATIONS["DRUID_BALANCE"] = {
    ['profileName'] = 'balance',
    ['init'] = E.initBalanceDruid,
    ['load'] = E.loadBalanceDruid,
    ['unload'] = E.unloadBalanceDruid,
    ['update'] = E.updateBalanceDruid,
    ['toggleFunctions'] = {}
}
