---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 02.03.2022 9:34
---
local _, E = ...

E.FERAL_DRUID_DATA = {}
feralDruid = E.FERAL_DRUID_DATA
feralDruid.switchButtons = {}
bf = E.BUTTON_FACTORY
st = E.SPELL_TOOLS

function feralDruid:init()
    print("Initializing FERAL")

    feralDruid.frame = CreateFrame("Frame", "FDruidFrame", UIParent)

    feralDruid.frame:SetFrameStrata("TOOLTIP")
    feralDruid.frame:SetWidth(150)
    feralDruid.frame:SetHeight(120)

    feralDruid.combatTexture = feralDruid.frame:CreateTexture(nil, "BACKGROUND")
    feralDruid.combatTexture:SetPoint("BOTTOMLEFT", 0, 90)
    feralDruid.combatTexture:SetSize(30, 30)


    feralDruid.activeTexture = feralDruid.frame:CreateTexture(nil, "BACKGROUND")
    feralDruid.activeTexture:SetPoint("BOTTOMLEFT", 30, 90)
    feralDruid.activeTexture:SetSize(120, 30)

    feralDruid.toggleButtons = {}
    feralDruid.activatingButtons = {}

    bf.setGlobalVariables(self, 30,30)

    local strategySwitchData =
    {
        { ['textValue'] = "cf", ['icon'] = 132115 },
        { ['textValue'] = "cr", ['icon'] = 132115 },
        { ['textValue'] = "bt", ['icon'] = 132115 },
    }

    feralDruid.switchButtons.strategySwitch = bf.createSwitch(self,0,2, feralDruid.frame, strategySwitchData)



    feralDruid.frame:SetPoint("CENTER", 0, 0)
    feralDruid.frame:SetMovable(true)
    feralDruid.frame:EnableMouse(true)
    feralDruid.frame:RegisterForDrag("LeftButton")
    feralDruid.frame:SetScript("OnDragStart", feralDruid.frame.StartMoving)
    feralDruid.frame:SetScript("OnDragStop", feralDruid.frame.StopMovingOrSizing)

    feralDruid.actualizeFrame()
    feralDruid.frame:Hide()

end

function feralDruid:load()
    feralDruid.frame:Show()
    print("Loading FERAL")
end

function feralDruid:unload()
    feralDruid.frame:Hide()
    print("Unloading FERAL")
end

function feralDruid:update()

    local serializationData = E.serializationData

    serializationData.profile = "fd_01";
    serializationData.feralStrategy = feralDruid.switchButtons.strategySwitch.textValue;
    serializationData.cp = GetComboPoints("player", "target");

    serializationData.ripp = st.isUsableSpell(self,"Rip");
    serializationData.manglep = st.isUsableBySpellAndDebuff(self,"Mangle (Cat)", "Mangle (Cat)", false, 0.5)
    serializationData.shredp = st.isUsableSpell(self,"Shred");
    serializationData.catFormp = st.isUsableSpell(self,"Cat Form");
    serializationData.form = GetShapeshiftForm(false);

    feralDruid.actualizeFrame()
end

function feralDruid:actualizeFrame()
    if UnitAffectingCombat("Player") then
        feralDruid.combatTexture:SetColorTexture(0,1,0,0.5)
    else
        feralDruid.combatTexture:SetColorTexture(1,0,0,0.5)
    end

    if E.active then
        feralDruid.activeTexture:SetColorTexture(0,1,0,0.5)
    else
        if UnitAffectingCombat("Player") then
            feralDruid.activeTexture:SetColorTexture(1,0.5,0,0.5)
        else
            feralDruid.activeTexture:SetColorTexture(1,0,0,0.5)
        end
    end

    feralDruid.switchButtons.strategySwitch.update();
end

E.CLASS_CONFIGURATIONS["DRUID_FERAL"] = {
    ['profileName'] = 'feral',
    ['init'] = feralDruid.init,
    ['load'] = feralDruid.load,
    ['unload'] = feralDruid.unload,
    ['update'] = feralDruid.update,
    ['toggleFunctions'] = {}
}
