---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vojta.
--- DateTime: 02.03.2022 9:34
---
local _, E = ...

E.PROTWAR_DATA = {}
st = E.SPELL_TOOLS

function E:initProtWar()
    E.PROTWAR_DATA.protWarriorFrame = CreateFrame("Frame", "nil", UIParent)

    E.PROTWAR_DATA.protWarriorFrame:SetFrameStrata("TOOLTIP")
    E.PROTWAR_DATA.protWarriorFrame:SetWidth(30)
    E.PROTWAR_DATA.protWarriorFrame:SetHeight(30)

    E.PROTWAR_DATA.activeTexture = E.PROTWAR_DATA.protWarriorFrame:CreateTexture(nil, "BACKGROUND")
    E.PROTWAR_DATA.activeTexture:SetPoint("BOTTOMLEFT", 0,0)
    E.PROTWAR_DATA.activeTexture:SetSize(30, 30)
    E.PROTWAR_DATA.protWarriorFrame.texture = E.PROTWAR_DATA.activeTexture

    E.PROTWAR_DATA.protWarriorFrame:SetPoint("CENTER", 0, 0)
    E.PROTWAR_DATA.protWarriorFrame:SetMovable(true)
    E.PROTWAR_DATA.protWarriorFrame:EnableMouse(true)
    E.PROTWAR_DATA.protWarriorFrame:RegisterForDrag("LeftButton")
    E.PROTWAR_DATA.protWarriorFrame:SetScript("OnDragStart", E.PROTWAR_DATA.protWarriorFrame.StartMoving)
    E.PROTWAR_DATA.protWarriorFrame:SetScript("OnDragStop", E.PROTWAR_DATA.protWarriorFrame.StopMovingOrSizing)
    E.PROTWAR_DATA.protWarriorFrame:Show()
end

function E:loadProtWar()
    print("Loading PROT WAR")
end

function E:unloadProtWar()
    print("Unloading PROT WAR")
end

function E:updateProtWar()
    E.serializationData.profile = "pw_01";

    E.serializationData.rev = st.isUsableSpell(self,"Revenge");
    E.serializationData.ss = st.isUsableSpell(self,"Shield Slam");
    E.serializationData.sb = st.isUsableSpell(self,"Shield Block");
    E.serializationData.dev = st.isUsableSpell(self,"Devastate");
    E.serializationData.hs = st.isUsableSpell(self,"Heroic Strike");

    if E.active then
        E.PROTWAR_DATA.activeTexture:SetColorTexture(0, 1, 0, 0.5);
    else
        E.PROTWAR_DATA.activeTexture:SetColorTexture(1, 0, 0, 0.5);
    end
end

print(E.CLASS_CONFIGURATIONS)
E.CLASS_CONFIGURATIONS["WARRIOR_PROT"] = {
    ['profileName'] = 'protwar',
    ['init'] = E.initProtWar,
    ['load'] = E.loadProtWar,
    ['unload'] = E.unloadProtWar,
    ['update'] = E.updateProtWar,
    ['toggleFunctions'] = {}
}

